modification_reasons = {
    '11': 'Initiation of Study medication ',
    '12': 'Completion of Study follow-up',
    '13': 'NVP scheduled modification',
    '14': 'Virological failure',
    '15': 'Toxicity related to other Study Medications',
    '16': 'Recycling',
    '50': 'Requires medication not permitted while taking study medications',
    '51': 'Concomitant codition (TB,pregnancy)',
    '52': 'Weight gain/loss',
    '60': 'Concomitant codition resolved',
    '70': 'Toxicity decreased/resolved',
    '80': 'Clinician discretion',
    '81': 'Patient request because of intolerance to study medication',
    '84': 'Patient request for other reason',
    '82': 'Non-compliance with clinic visits',
    '83': 'Non-compliance with Study medications',
    '20': 'Anemia',
    '21': 'Bleeding',
    '23': 'Diarrhea',
    '24': 'Fatigue',
    '25': 'Fever',
    '38': 'Glucose intolerance/diabetes',
    '26': 'Headache',
    '36': 'Hypertriglyceridemia',
    '37': 'Hypercholesterolemia',
    '27': 'Hepatotoxicity (not lactic acidosis)',
    '42': 'Hypersensitivity reaction',
    '33': 'Lactic acidosis',
    '35': 'Myositis',
    '28': 'Nausea',
    '41': 'Nephrotoxicity',
    '29': 'Neutropenia',
    '22': 'Neuropsychiatric symptoms',
    '39': 'Pancreatitis',
    '34': 'Peripheral neuropathy',
    '40': 'Rash',
    '30': 'Thrombocytopenia',
    '31': 'Vomiting',
    '98': 'Other toxicity, specify',
    '90': 'Death',
    '0': 'Normal',
    '1': 'Mild',
    '2': 'Moderate',
    '3': 'Severe',
    '-3': 'Not applicable'}
